#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
script_dir=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
root=$(git -C "$script_dir" rev-parse --show-toplevel)
control="$script_dir/codebase-index.sh"
umask 077
mkdir -p "$root/.claude/cache/codebase-index"
ENV_FILE="$root/.claude/cache/codebase-index/setup.env"

choice() {
  local key="$1" prompt="$2" default="$3" valid="$4"
  while true; do
    ask "$key" "$prompt [$default]:"
    [[ -n "${!key}" ]] || printf -v "$key" '%s' "$default"
    if [[ " ${valid} " == *" ${!key} "* ]]; then break; fi
    warn "Choose one of: $valid"
  done
  write_env "$key" "${!key}"
}

banner "Codebase index setup"

stage "Review this checkout"
say "Checkout: $root"
say "Settings stay in the ignored codebase-index cache, not Laravel's .env."
bash "$control" status
pause "Review the settings, then press Enter."

stage "Choose automatic indexing"
say "OpenCode will build on startup and refresh after edits and outside changes."
choice CBX_AUTO "Automatic indexing, on or off" on "on off"

stage "Choose embeddings"
say "Off keeps symbol and text retrieval. Ollama uses your installed model."
choice CBX_PROVIDER "Embeddings, off, local, ollama, or external" off "off local ollama external"

stage "Choose the provider model"
case "$CBX_PROVIDER" in
  off) say "No model or endpoint needed." ;;
  ollama)
    open_url "https://docs.ollama.com/api/openai-compatibility"
    step "Use the exact model tag from 'ollama list'."
    if command -v ollama >/dev/null 2>&1; then ollama list || warn "Start Ollama, then rerun."; fi
    ask CBX_MODEL "Model [unclemusclez/jina-embeddings-v2-base-code:latest]:"
    CBX_MODEL=${CBX_MODEL:-unclemusclez/jina-embeddings-v2-base-code:latest}
    ask CBX_ENDPOINT "Endpoint [http://localhost:11434/v1/embeddings]:"
    CBX_ENDPOINT=${CBX_ENDPOINT:-http://localhost:11434/v1/embeddings}
    write_env CBX_MODEL "$CBX_MODEL"
    write_env CBX_ENDPOINT "$CBX_ENDPOINT"
    ;;
  local)
    open_url "https://www.sbert.net/docs/sentence_transformer/pretrained_models.html"
    step "Choose a Sentence Transformers model ID. Loading it may download model files."
    ask CBX_MODEL "Model [all-MiniLM-L6-v2]:"
    CBX_MODEL=${CBX_MODEL:-all-MiniLM-L6-v2}
    write_env CBX_MODEL "$CBX_MODEL"
    ;;
  external)
    step "Use your provider's full OpenAI-compatible embeddings endpoint and model ID."
    ask CBX_ENDPOINT "HTTPS embeddings endpoint:"
    ask CBX_MODEL "Model ID:"
    [[ -n "$CBX_ENDPOINT" && -n "$CBX_MODEL" ]] || { warn "Endpoint and model are required."; exit 1; }
    write_env CBX_ENDPOINT "$CBX_ENDPOINT"
    write_env CBX_MODEL "$CBX_MODEL"
    ;;
esac

stage "Configure authentication"
if [[ "$CBX_PROVIDER" == external ]]; then
  saved_env=$ENV_FILE
  ENV_FILE="$root/.claude/cache/codebase-index/credentials.env"
  ask_secret CBX_EMBEDDINGS_API_KEY "API key, hidden input:"
  [[ -n "$CBX_EMBEDDINGS_API_KEY" ]] || { warn "An API key is required."; exit 1; }
  ENV_FILE=$saved_env
  say "The key stays in memory until you confirm and validation succeeds."
else
  say "No secret required. The local Ollama preset supplies a placeholder automatically."
fi

stage "Validate and apply"
say "Provider: $CBX_PROVIDER. Automatic indexing: $CBX_AUTO."
say "Enabled embeddings send indexed code chunks to the selected provider."
say "Changing providers or models rebuilds vectors. Your source files stay untouched."
confirm "Validate the provider, save these settings, and refresh the index?" || exit 0
args=(configure --auto "$CBX_AUTO" --embeddings "$CBX_PROVIDER")
if [[ "$CBX_PROVIDER" != off ]]; then args+=(--model "$CBX_MODEL"); fi
if [[ "$CBX_PROVIDER" == ollama || "$CBX_PROVIDER" == external ]]; then args+=(--endpoint "$CBX_ENDPOINT"); fi
if [[ "$CBX_PROVIDER" == external ]]; then
  printf '%s\n' "$CBX_EMBEDDINGS_API_KEY" | bash "$control" "${args[@]}" --credential-stdin
  unset CBX_EMBEDDINGS_API_KEY
else
  bash "$control" "${args[@]}"
fi
bash "$control" refresh

stage "Review the result"
bash "$control" status
say "OpenCode owns ongoing indexing. Agents only retrieve evidence."
pause "Press Enter for the closing summary."
finish
